# Generated by Django 6.0 on 2025-12-14 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moviess',
            new_name='Movies',
        ),
    ]
